// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MemoryController from "./memory_controller"
application.register("memory", MemoryController)

import PaintController from "./paint_controller"
application.register("paint", PaintController)

import SoloController from "./solo_controller"
application.register("solo", SoloController)
